
select * from MEMBER;
CREATE TABLE MEMBER(
	MEMBER_EMAIL VARCHAR2(100) PRIMARY KEY,
	MEMBER_NICKNAME VARCHAR2(100) NOT NULL,
	MEMBER_NAME VARCHAR2(100) NOT NULL,
	MEMBER_BIRTH DATE NOT NULL,
	MEMBER_PNUMBER VARCHAR2(100) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(100) NOT NULL,
	MEMBER_AUTH VARCHAR2(100) NOT NULL, -- 0:일반회원, 1:판매자, 2:관리자, -1:불량회원
	MEMBER_POINT NUMBER DEFAULT 0,
	MEMBER_CASH NUMBER DEFAULT 0,
	MEMBER_JOINDATE DATE NOT NULL,
	MEMBER_LOGINTIME_INFO DATE,
	MEMBER_DAILY_ATTENDED_COUNT NUMBER DEFAULT 0
);


insert into MEMBER(MEMBER_EMAIL, MEMBER_NICKNAME, MEMBER_NAME, MEMBER_BIRTH, MEMBER_PNUMBER,
MEMBER_PASSWORD, MEMBER_AUTH, 	MEMBER_POINT, 	MEMBER_CASH, MEMBER_JOINDATE, 
MEMBER_LOGINTIME_INFO, MEMBER_DAILY_ATTENDED_COUNT)
values('a@gmail.com', 'A맨', '리제성', to_date('1988/01/09', 'yyyy/mm/dd'), '01043018809', 'aaaa', 0, 
100, 10000, sysdate, sysdate, 1);



